// ─── Solid icons ────────────────────────────────────────────────────────────
export {
  faSearch,
  faShoppingCart,
  faBars,
  faTruck,
  faShieldAlt,
  faShield,
  faCreditCard,
  faCheck,
  faArrowRight,
  faArrowLeft,
  faTag,
  faBox,
  faBoxOpen,
  faHeadphones,
  faMobileAlt,
  faTshirt,
  faPlug,
  faGem,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faFire,
  faGift,
  faHeart,
  faMapMarkerAlt,
  faUser,
  faExternalLinkAlt,
  faTrash,
  faEdit,
  faPlus,
  faMinus,
  faTimes,
  faEye,
  faShare,
  faCopy,
  faTachometerAlt,
  faSignOutAlt,
  faExclamationTriangle,
  faChartLine,
  faShoppingBag,
  faPhone,
  faClock,
  faHome,
  faStar,
  faSpinner,
  faUpload,
  faCheckCircle,
  faCommentDots,
  faSlidersH,
  faVolumeUp,
  faExclamationCircle,
  faLightbulb,
  faRocket,
  faLock,
  faGear,
  faBell,
  faUsers,
  faHeartBroken,
} from '@fortawesome/free-solid-svg-icons';

// ─── Brand icons ─────────────────────────────────────────────────────────────
export {
  faWhatsapp,
  faFacebook,
  faTiktok,
  faInstagram,
} from '@fortawesome/free-brands-svg-icons';
