import type { Product } from '@/src/types';

export interface MockCategory {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  bg: string;
}

export const MOCK_CATEGORIES: MockCategory[] = [
  { id: '1', name: 'Smartphones',    slug: 'smartphones',    emoji: '📱', bg: 'bg-blue-50'   },
  { id: '2', name: 'Accessoires',    slug: 'accessoires',    emoji: '🎧', bg: 'bg-purple-50' },
  { id: '3', name: 'Audio',          slug: 'audio',          emoji: '🔊', bg: 'bg-green-50'  },
  { id: '4', name: 'Électroménager', slug: 'electromenager', emoji: '🏠', bg: 'bg-orange-50' },
  { id: '5', name: 'Mode',           slug: 'mode',           emoji: '👗', bg: 'bg-pink-50'   },
  { id: '6', name: 'Beauté',         slug: 'beaute',         emoji: '✨', bg: 'bg-yellow-50' },
];

export const SLUG_TO_ID: Record<string, string> = {
  smartphones:    '1',
  accessoires:    '2',
  audio:          '3',
  electromenager: '4',
  mode:           '5',
  beaute:         '6',
};

export const MOCK_PRODUCTS: Product[] = [
  // ── Smartphones (5) ──────────────────────────────────────
  {
    id: '1',
    slug: 'iphone-15-pro-max',
    name: 'iPhone 15 Pro Max 256 Go',
    description: 'La puce A17 Pro repousse les limites de la performance mobile avec son GPU 6 cœurs et son moteur neural ultrarapide. L\'appareil photo ProRAW 48 MP capture des détails saisissants même en basse lumière, tandis que le châssis en titane naturel offre une solidité inégalée pour un poids plume.',
    price: 4_500_000,
    image_url: 'https://picsum.photos/seed/iphone15promax/400/400',
    images: [
      'https://picsum.photos/seed/iphone15promax/400/400',
      'https://picsum.photos/seed/iphone15promax-b/400/400',
      'https://picsum.photos/seed/iphone15promax-c/400/400',
    ],
    characteristics: {
      'Processeur':  'A17 Pro (6 cœurs, 3 nm)',
      'Stockage':    '256 Go NVMe',
      'Écran':       '6.7" Super Retina XDR ProMotion',
      'RAM':         '8 Go LPDDR5',
      'Charge':      '27W filaire + 15W MagSafe',
    },
    category_id: '1',
    stock: 3,
    is_active: true,
    is_featured: true,
    created_at: '2025-04-10T10:00:00Z',
  },
  {
    id: '2',
    slug: 'samsung-galaxy-a55',
    name: 'Samsung Galaxy A55 5G',
    description: 'Le Galaxy A55 5G embarque un écran AMOLED Vision Booster 120 Hz qui reste parfaitement lisible en plein soleil. Sa triple caméra 50 MP avec stabilisation optique et sa batterie 5 000 mAh le placent comme le meilleur rapport qualité-prix de la gamme Galaxy.',
    price: 2_200_000,
    promo_price: 1_990_000,
    image_url: 'https://picsum.photos/seed/galaxya55/400/400',
    images: [
      'https://picsum.photos/seed/galaxya55/400/400',
      'https://picsum.photos/seed/galaxya55-b/400/400',
      'https://picsum.photos/seed/galaxya55-c/400/400',
    ],
    characteristics: {
      'Processeur':  'Exynos 1480 (4 nm)',
      'Stockage':    '256 Go',
      'Écran':       '6.6" AMOLED 120 Hz',
      'RAM':         '8 Go',
      'Batterie':    '5 000 mAh',
    },
    category_id: '1',
    stock: 8,
    is_active: true,
    created_at: '2025-03-20T09:00:00Z',
  },
  {
    id: '3',
    slug: 'tecno-camon-30',
    name: 'Tecno Camon 30 Pro',
    description: 'Le Camon 30 Pro mise tout sur la photographie avec sa caméra RGBS 50 MP et son mode portrait IA de nouvelle génération. L\'écran AMOLED 144 Hz offre une fluidité exceptionnelle, et la charge 33W recharge la batterie 5 000 mAh en moins d\'une heure.',
    price: 1_100_000,
    image_url: 'https://picsum.photos/seed/tecnocamon30/400/400',
    images: [
      'https://picsum.photos/seed/tecnocamon30/400/400',
      'https://picsum.photos/seed/tecnocamon30-b/400/400',
      'https://picsum.photos/seed/tecnocamon30-c/400/400',
    ],
    characteristics: {
      'Processeur':  'Helio G99 Ultimate',
      'Stockage':    '256 Go',
      'Écran':       '6.78" AMOLED 144 Hz',
      'RAM':         '8 Go',
      'Charge':      '33W',
    },
    category_id: '1',
    stock: 15,
    is_active: true,
    created_at: '2025-03-05T12:00:00Z',
  },
  {
    id: '4',
    slug: 'xiaomi-redmi-note-13',
    name: 'Xiaomi Redmi Note 13 Pro',
    description: 'Le Redmi Note 13 Pro impose un capteur 200 MP inédit dans cette gamme de prix, livrant des photos d\'une précision extraordinaire. Le Snapdragon 7s Gen 2 gère les tâches intensives avec aisance, et la charge 67W restitue 100 % de batterie en moins de 50 minutes.',
    price: 950_000,
    image_url: 'https://picsum.photos/seed/redminote13/400/400',
    images: [
      'https://picsum.photos/seed/redminote13/400/400',
      'https://picsum.photos/seed/redminote13-b/400/400',
      'https://picsum.photos/seed/redminote13-c/400/400',
    ],
    characteristics: {
      'Processeur':  'Snapdragon 7s Gen 2',
      'Stockage':    '256 Go',
      'Écran':       '6.67" AMOLED 120 Hz',
      'RAM':         '12 Go',
      'Charge':      '67W',
    },
    category_id: '1',
    stock: 0,
    is_active: true,
    created_at: '2025-02-14T08:00:00Z',
  },
  {
    id: '5',
    slug: 'infinix-smart-8',
    name: 'Infinix Smart 8 Plus',
    description: 'L\'Infinix Smart 8 Plus démocratise l\'accès aux smartphones modernes avec son grand écran HD+ 90 Hz et sa batterie 5 000 mAh qui tient facilement deux jours. Sa caméra 50 MP et son stockage 128 Go en font l\'entrée de gamme idéale pour les usages quotidiens.',
    price: 550_000,
    image_url: 'https://picsum.photos/seed/infinixsmart8/400/400',
    images: [
      'https://picsum.photos/seed/infinixsmart8/400/400',
      'https://picsum.photos/seed/infinixsmart8-b/400/400',
      'https://picsum.photos/seed/infinixsmart8-c/400/400',
    ],
    characteristics: {
      'Processeur':  'Helio G36',
      'Stockage':    '128 Go',
      'Écran':       '6.6" HD+ 90 Hz',
      'RAM':         '4 Go',
      'Batterie':    '5 000 mAh',
    },
    category_id: '1',
    stock: 22,
    is_active: true,
    created_at: '2025-01-25T14:00:00Z',
  },

  // ── Audio (3) ─────────────────────────────────────────────
  {
    id: '6',
    slug: 'airpods-pro-2',
    name: 'AirPods Pro 2ème génération',
    description: 'La puce H2 propulse la réduction de bruit active adaptative des AirPods Pro 2 à un niveau que personne d\'autre n\'atteint — le son ambiant s\'efface totalement en quelques millisecondes. Le son spatial personnalisé crée une immersion tridimensionnelle unique, et le boîtier MagSafe USB-C offre jusqu\'à 30 heures d\'autonomie cumulée.',
    price: 850_000,
    promo_price: 720_000,
    image_url: 'https://picsum.photos/seed/airpodspro2/400/400',
    images: [
      'https://picsum.photos/seed/airpodspro2/400/400',
      'https://picsum.photos/seed/airpodspro2-b/400/400',
      'https://picsum.photos/seed/airpodspro2-c/400/400',
    ],
    characteristics: {
      'Puce':          'Apple H2',
      'ANC':           'Actif adaptatif',
      'Autonomie':     '6h (30h avec boîtier)',
      'Connectivité':  'Bluetooth 5.3',
      'Résistance':    'IPX4',
    },
    category_id: '3',
    stock: 5,
    is_active: true,
    is_featured: true,
    created_at: '2025-04-01T11:00:00Z',
  },
  {
    id: '7',
    slug: 'jbl-charge-5',
    name: 'Enceinte JBL Charge 5',
    description: 'La JBL Charge 5 projette un son Pro JBL puissant et équilibré avec ses 40W RMS, idéale pour animer une soirée en intérieur ou en extérieur. Sa certification IP67 la rend totalement étanche à la poussière et à l\'immersion, et sa sortie USB-A charge vos appareils pendant la lecture.',
    price: 680_000,
    image_url: 'https://picsum.photos/seed/jblcharge5/400/400',
    images: [
      'https://picsum.photos/seed/jblcharge5/400/400',
      'https://picsum.photos/seed/jblcharge5-b/400/400',
      'https://picsum.photos/seed/jblcharge5-c/400/400',
    ],
    characteristics: {
      'Puissance':     '40W RMS',
      'Autonomie':     '20 heures',
      'Étanchéité':   'IP67',
      'Connectivité':  'Bluetooth 5.1',
      'Charge':        'USB-C (entrée) + USB-A (sortie)',
    },
    category_id: '3',
    stock: 0,
    is_active: true,
    created_at: '2025-02-01T10:00:00Z',
  },
  {
    id: '8',
    slug: 'sony-wh1000xm5',
    name: 'Casque Sony WH-1000XM5',
    description: 'Le WH-1000XM5 est le roi incontesté de la réduction de bruit grâce à ses 8 micros et deux processeurs dédiés qui analysent et neutralisent jusqu\'à 98 % des bruits ambiants. Avec 30 heures d\'autonomie et une qualité d\'appel cristalline en mains libres, il est aussi bien taillé pour le bureau que les longs voyages.',
    price: 1_500_000,
    promo_price: 1_350_000,
    image_url: 'https://picsum.photos/seed/sonywh1000xm5/400/400',
    images: [
      'https://picsum.photos/seed/sonywh1000xm5/400/400',
      'https://picsum.photos/seed/sonywh1000xm5-b/400/400',
      'https://picsum.photos/seed/sonywh1000xm5-c/400/400',
    ],
    characteristics: {
      'ANC':           '8 micros + 2 processeurs',
      'Autonomie':     '30h (ANC activé)',
      'Connectivité':  'Bluetooth 5.2 + Jack 3.5mm',
      'Poids':         '250g',
      'Charge':        'USB-C (3h pour 30h)',
    },
    category_id: '3',
    stock: 7,
    is_active: true,
    created_at: '2025-03-15T09:30:00Z',
  },

  // ── Accessoires (4) ───────────────────────────────────────
  {
    id: '9',
    slug: 'coque-iphone-15-pro',
    name: 'Coque iPhone 15 Pro Max Premium',
    description: 'Cette coque en silicone mat double couche absorbe les chocs et protège les angles les plus exposés de votre iPhone 15 Pro Max sans ajouter de volume inutile. Entièrement compatible MagSafe, elle laisse passer la charge sans fil et s\'accroche instantanément aux accessoires de l\'écosystème Apple.',
    price: 85_000,
    image_url: 'https://picsum.photos/seed/coqueiphone15/400/400',
    images: [
      'https://picsum.photos/seed/coqueiphone15/400/400',
      'https://picsum.photos/seed/coqueiphone15-b/400/400',
      'https://picsum.photos/seed/coqueiphone15-c/400/400',
    ],
    characteristics: {
      'Compatibilité':       'iPhone 15 Pro Max',
      'Matière':             'Silicone mat double couche',
      'MagSafe':             'Compatible',
      'Couleurs disponibles': '6 coloris',
      'Poids':               '35g',
    },
    category_id: '2',
    stock: 34,
    is_active: true,
    created_at: '2025-01-10T15:00:00Z',
  },
  {
    id: '10',
    slug: 'anker-powerbank-20000',
    name: 'Power Bank Anker 737 20 000 mAh',
    description: 'L\'Anker 737 est la batterie externe ultime pour les utilisateurs exigeants : 140W de puissance max pour charger un MacBook Pro en moins de 90 minutes ou deux appareils simultanément à pleine vitesse. Son écran LED affiche en temps réel la capacité restante et la puissance délivrée à chaque port.',
    price: 280_000,
    image_url: 'https://picsum.photos/seed/anker737/400/400',
    images: [
      'https://picsum.photos/seed/anker737/400/400',
      'https://picsum.photos/seed/anker737-b/400/400',
      'https://picsum.photos/seed/anker737-c/400/400',
    ],
    characteristics: {
      'Capacité':        '20 000 mAh',
      'Puissance max':   '140W',
      'Ports':           '2× USB-C + 1× USB-A',
      'Poids':           '641g',
      'Recharge complète': '1h30',
    },
    category_id: '2',
    stock: 19,
    is_active: true,
    created_at: '2025-02-20T08:00:00Z',
  },
  {
    id: '11',
    slug: 'huawei-band-8',
    name: 'Huawei Band 8',
    description: 'Le Band 8 de Huawei tient 14 jours sur une seule charge grâce à son écran AMOLED ultra-efficace et son design ultra-fin de seulement 6,99 mm. Il surveille en continu votre fréquence cardiaque, votre saturation en oxygène (SpO2) et la qualité de votre sommeil pour vous aider à rester en forme.',
    price: 420_000,
    image_url: 'https://picsum.photos/seed/huaweiband8/400/400',
    images: [
      'https://picsum.photos/seed/huaweiband8/400/400',
      'https://picsum.photos/seed/huaweiband8-b/400/400',
      'https://picsum.photos/seed/huaweiband8-c/400/400',
    ],
    characteristics: {
      'Écran':           'AMOLED 1.47" couleur',
      'Autonomie':       '14 jours',
      'Suivi santé':     'SpO2, cardio, sommeil',
      'Résistance':      '5ATM',
      'Compatibilité':   'Android 6+ / iOS 13+',
    },
    category_id: '2',
    stock: 11,
    is_active: true,
    is_featured: true,
    created_at: '2025-03-01T12:00:00Z',
  },
  {
    id: '12',
    slug: 'support-telephone',
    name: 'Support Téléphone Bureau Réglable',
    description: 'Ce support en alliage d\'aluminium brossé offre une rotation à 360° et une inclinaison réglable pour trouver l\'angle de visionnage parfait, que ce soit pour les appels vidéo, la lecture ou le travail. Compatible avec tous les smartphones de 4 à 7 pouces et les petites tablettes, il s\'installe sans outil en quelques secondes.',
    price: 65_000,
    image_url: 'https://picsum.photos/seed/supporttel/400/400',
    images: [
      'https://picsum.photos/seed/supporttel/400/400',
      'https://picsum.photos/seed/supporttel-b/400/400',
      'https://picsum.photos/seed/supporttel-c/400/400',
    ],
    characteristics: {
      'Rotation':         '360°',
      'Compatibilité':    'Smartphones 4–7 pouces',
      'Matière':          'Alliage aluminium + ABS',
      'Hauteur':          'Réglable 10–30 cm',
      'Charge maximale':  '500g',
    },
    category_id: '2',
    stock: 0,
    is_active: true,
    created_at: '2025-01-05T10:00:00Z',
  },

  // ── Électroménager (3) ────────────────────────────────────
  {
    id: '13',
    slug: 'aspirateur-robot-xiaomi-s10',
    name: 'Aspirateur Robot Xiaomi S10+',
    description: 'Le Xiaomi S10+ combine une aspiration de 4 000 Pa et un système de lavage automatique de serpillère pour aspirer et laver vos sols en une seule passe. Sa navigation LiDAR cartographie votre domicile avec précision et évite les obstacles même dans l\'obscurité totale — pilotable depuis l\'app Mi Home.',
    price: 2_800_000,
    promo_price: 2_500_000,
    image_url: 'https://picsum.photos/seed/xiaomis10robot/400/400',
    images: [
      'https://picsum.photos/seed/xiaomis10robot/400/400',
      'https://picsum.photos/seed/xiaomis10robot-b/400/400',
      'https://picsum.photos/seed/xiaomis10robot-c/400/400',
    ],
    characteristics: {
      'Aspiration':     '4 000 Pa',
      'Autonomie':      '180 minutes',
      'Navigation':     'LiDAR 360°',
      'Capacité eau':   '200 ml',
      'Connectivité':   'WiFi + App Mi Home',
    },
    category_id: '4',
    stock: 2,
    is_active: true,
    is_featured: true,
    created_at: '2025-04-05T09:00:00Z',
  },
  {
    id: '14',
    slug: 'blender-tefal-1000w',
    name: 'Blender Tefal 1000W',
    description: 'Le blender Tefal 1000W réduit en quelques secondes fruits, glace et légumes grâce à son moteur puissant et ses 6 lames inox tranchantes. Le bol en inox 1,75 L est hermétique et résistant aux taches, et la fonction auto-nettoyage préserve vos lames sans démontage.',
    price: 350_000,
    image_url: 'https://picsum.photos/seed/tefal1000w/400/400',
    images: [
      'https://picsum.photos/seed/tefal1000w/400/400',
      'https://picsum.photos/seed/tefal1000w-b/400/400',
      'https://picsum.photos/seed/tefal1000w-c/400/400',
    ],
    characteristics: {
      'Puissance':   '1 000W',
      'Capacité':    '1.75L',
      'Lames':       '6 lames inox',
      'Vitesses':    '3 + fonction Pulse',
      'Garantie':    '2 ans',
    },
    category_id: '4',
    stock: 14,
    is_active: true,
    created_at: '2025-02-10T11:00:00Z',
  },
  {
    id: '15',
    slug: 'clim-hisense-12000',
    name: 'Climatiseur Hisense 12000 BTU',
    description: 'Ce climatiseur Hisense Inverter de classe A++ réduit votre consommation électrique jusqu\'à 40 % par rapport aux modèles conventionnels, tout en maintenant une température stable et silencieuse. Il couvre jusqu\'à 35 m² en mode froid ou chaud et se contrôle à distance via l\'application HiSmart.',
    price: 3_200_000,
    image_url: 'https://picsum.photos/seed/hisenseclim/400/400',
    images: [
      'https://picsum.photos/seed/hisenseclim/400/400',
      'https://picsum.photos/seed/hisenseclim-b/400/400',
      'https://picsum.photos/seed/hisenseclim-c/400/400',
    ],
    characteristics: {
      'Puissance':            '12 000 BTU',
      'Classe énergétique':   'A++',
      'Surface':              "Jusqu'à 35 m²",
      'WiFi':                 'Intégré (app HiSmart)',
      'Réversible':           'Climatisation + Chauffage',
    },
    category_id: '4',
    stock: 4,
    is_active: true,
    created_at: '2025-01-20T14:00:00Z',
  },

  // ── Mode (3) ──────────────────────────────────────────────
  {
    id: '16',
    slug: 'boubou-brode-homme',
    name: 'Boubou Brodé Homme Guinéen',
    description: 'Ce boubou en bazin riche 100 % coton est entièrement brodé à la main selon les motifs traditionnels guinéens, conférant à chaque pièce un caractère unique. Sa coupe ample et respirante convient parfaitement au climat tropical, disponible du S au XXL en blanc, bleu roi et bordeaux.',
    price: 280_000,
    image_url: 'https://picsum.photos/seed/boubouguinee/400/400',
    images: [
      'https://picsum.photos/seed/boubouguinee/400/400',
      'https://picsum.photos/seed/boubouguinee-b/400/400',
      'https://picsum.photos/seed/boubouguinee-c/400/400',
    ],
    characteristics: {
      'Tissu':       'Bazin riche 100% coton',
      'Broderie':    'Main, artisanat traditionnel',
      'Tailles':     'S, M, L, XL, XXL',
      'Coloris':     'Blanc, bleu roi, bordeaux',
      'Entretien':   'Lavage à la main conseillé',
    },
    category_id: '5',
    stock: 18,
    is_active: true,
    created_at: '2025-03-25T10:00:00Z',
  },
  {
    id: '17',
    slug: 'robe-wax-africaine',
    name: 'Robe Wax Africaine Moderne',
    description: 'Confectionnée dans un wax hollandais 100 % coton aux couleurs vives et durables, cette robe allie la richesse du textile africain à une coupe moderne parfaitement ajustée. Disponible en 5 motifs distincts et en tailles XS à XXL, elle s\'adapte à toutes les silhouettes pour les cérémonies comme le quotidien.',
    price: 180_000,
    promo_price: 150_000,
    image_url: 'https://picsum.photos/seed/robewax/400/400',
    images: [
      'https://picsum.photos/seed/robewax/400/400',
      'https://picsum.photos/seed/robewax-b/400/400',
      'https://picsum.photos/seed/robewax-c/400/400',
    ],
    characteristics: {
      'Tissu':     'Wax hollandais 100% coton',
      'Coupe':     'Moderne et ajustée',
      'Tailles':   'XS à XXL',
      'Motifs':    '5 coloris au choix',
      'Entretien': 'Lavage délicat 30°C',
    },
    category_id: '5',
    stock: 25,
    is_active: true,
    created_at: '2025-02-28T09:00:00Z',
  },
  {
    id: '18',
    slug: 'sac-cuir-marron',
    name: 'Sac à Main Cuir Artisanal',
    description: 'Fabriqué à la main en Guinée par des artisans locaux, ce sac en cuir véritable tanné végétal développe une belle patine au fil du temps qui le rend unique. Sa bandoulière amovible et réglable et ses fermetures zips YKK en font un compagnon quotidien alliant esthétique et praticité.',
    price: 320_000,
    image_url: 'https://picsum.photos/seed/sacmain/400/400',
    images: [
      'https://picsum.photos/seed/sacmain/400/400',
      'https://picsum.photos/seed/sacmain-b/400/400',
      'https://picsum.photos/seed/sacmain-c/400/400',
    ],
    characteristics: {
      'Matière':       'Cuir véritable tanné végétal',
      'Dimensions':    '35 × 25 × 12 cm',
      'Bandoulière':   'Amovible, réglable',
      'Fermeture':     'Zips YKK',
      'Fabrication':   'Artisanale locale, Guinée',
    },
    category_id: '5',
    stock: 8,
    is_active: true,
    created_at: '2025-01-15T13:00:00Z',
  },

  // ── Beauté (2) ────────────────────────────────────────────
  {
    id: '19',
    slug: 'kit-soin-shea',
    name: 'Kit Soin Visage Karité & Aloe',
    description: 'Ce kit 100 % naturel réunit le beurre de karité pur de Guinée, le gel d\'aloe vera apaisant et l\'huile de coco hydratante pour une routine visage complète sans produits chimiques. Sans parabènes ni conservateurs artificiels, il convient à tous les types de peau, y compris les peaux sensibles.',
    price: 95_000,
    image_url: 'https://picsum.photos/seed/kitsoinshea/400/400',
    images: [
      'https://picsum.photos/seed/kitsoinshea/400/400',
      'https://picsum.photos/seed/kitsoinshea-b/400/400',
      'https://picsum.photos/seed/kitsoinshea-c/400/400',
    ],
    characteristics: {
      'Contenu':       'Karité 50ml + Aloe 100ml + Coco 30ml',
      'Type de peau':  'Tous types',
      'Composition':   '100% naturel, sans parabènes',
      'Origine':       'Produit local guinéen',
      'Conservation':  '12 mois après ouverture',
    },
    category_id: '6',
    stock: 40,
    is_active: true,
    created_at: '2025-03-10T08:00:00Z',
  },
  {
    id: '20',
    slug: 'parfum-oud-khalijee',
    name: 'Parfum Oud El Khalijee',
    description: 'Oud El Khalijee est une eau de parfum concentrée aux accords orientaux profonds : la chaleur enveloppante de l\'oud se mêle au musc blanc et à l\'ambre pour une signature olfactive inoubliable. Sa longue tenue de 8 à 12 heures en fait un parfum du matin au soir, parfait pour les grandes occasions.',
    price: 250_000,
    image_url: 'https://picsum.photos/seed/parfumoud/400/400',
    images: [
      'https://picsum.photos/seed/parfumoud/400/400',
      'https://picsum.photos/seed/parfumoud-b/400/400',
      'https://picsum.photos/seed/parfumoud-c/400/400',
    ],
    characteristics: {
      'Volume':        '100 ml',
      'Concentration': 'Eau de parfum',
      'Notes':         'Oud, musc blanc, ambre, santal',
      'Tenue':         '8 à 12 heures',
      'Origine':       'Artisanat du Moyen-Orient',
    },
    category_id: '6',
    stock: 12,
    is_active: true,
    created_at: '2025-02-05T10:00:00Z',
  },
];

export function getCategoryCount(categoryId: string): number {
  return MOCK_PRODUCTS.filter((p) => p.category_id === categoryId && p.is_active).length;
}
